{% set name = "pytopomap" %}
{% set version = "0.0.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytopomap-{{ version }}.tar.gz
  sha256: e931f9cad7e226dda9adc6cb29e839b7e5db2e01d73cad3e54c8bac426f2ccb9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=80.8.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - plotly

test:
  imports:
    - pytopomap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/marcperuz/pytopomap
  summary: Topographic visualization tools
  description: |
    pytopomap is a python package designed to plot nice topographic maps along with
    raster data on it.
  license: LGPL-2.1-only
  license_file: LICENSE
  doc_url: https://pytopomap.readthedocs.io/
  dev_url: https://github.com/marcperuz/pytopomap

extra:
  recipe-maintainers:
    - marcperuz
    - Cykap
